### ISSUE TITLE
Website title not being updated

### ISSUE THREAD

**Issue by aravindthokala** [austingebauer/devise#6] opened 2020-08-03 17:02 UTC
In the config file, even though the website title field is updated with my name, it shows my website link instead of my name.

**Comment by austingebauer** [comment] 2020-08-03 21:59
Hi, @aravindthokala! 

Can you confirm that your config includes `title = ""` at the top level? The title field should be set appropriately (see https://github.com/austingebauer/devise/blob/master/layouts/partials/head.html#L2). I'm also populating `title = "Austin Gebauer"` for [austingebauer.com](https://austingebauer.com/), for which you can see it has the correct title.

**Comment by aravindthokala** [comment] 2020-08-04 17:14
Yes, the config.toml has 
title = "Aravind Thokala"

**Comment by austingebauer** [comment] 2020-08-06 00:45
Hmm, interesting! I'm not able to reproduce where the title is not what's specified in the `title = ""` setting in the config.

For example, my config looks like:
```toml
baseURL = "http://austingebauer.com/"
languageCode = "en-us"
title = "Austin Gebauer"
theme = "devise"
relativeURLs = true
enableEmoji = true
enableRobotsTXT = true
copyright = "&copy; Copyright 2020, Austin Gebauer"
```

Any additional details you can provide as to why this might be happening?

**Comment by aravindthokala** [comment] 2020-08-06 05:32
Mine is this:

```
baseURL = "https://aravindthokala.me/"
title = "Aravind Thokala"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "&copy; 2020, Aravind Thokala"

```
Above the themes directory, I have content/ and static/ which are copies from the exampleSite/.

**Comment by austingebauer** [comment] 2020-08-11 02:47
That config looks like it should work correctly. Can you confirm that your version of the devise theme has has the file https://github.com/austingebauer/devise/blob/master/layouts/partials/head.html#L2 that includes `<title>{{ .Title }}</title>`?

**Comment by aravindthokala** [comment] 2020-08-13 15:47
Yes, it has.

I had to do this in that HTML file to make it work:

<title>Aravind Thokala</title>

**Comment by austingebauer** [comment] 2020-10-02 18:22
I'm still not able to reproduce this one, @aravindthokala. Let me know if it's still an issue.

**Comment by austingebauer** [comment] 2020-10-09 16:42
Closing this one. Feel free to reopen!

**Closed by austingebauer** 2020-10-09 16:42 UTC
